# Generated by Django 2.1.5 on 2019-01-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0002_auto_20190122_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmi',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
